version: '3.8'

services:
  microservice:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring-boot-microservice
    ports:
      - "8080:8080"
      - "9990:9990"
    environment:
      - JAVA_OPTS=-Xms512m -Xmx1024m
    networks:
      - microservice-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/microservice/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  microservice-network:
    driver: bridge
